DROP TABLE IF EXISTS [STATES];
DROP TABLE IF EXISTS [ICD10S];
DROP TABLE IF EXISTS [ENCOUNTERS];

-- Create ICD10S table
CREATE TABLE IF NOT EXISTS ICD10S (
    Code VARCHAR(3) PRIMARY KEY,
    Description VARCHAR(255)
);

-- Create PATIENTS table
CREATE TABLE IF NOT EXISTS PATIENTS (
    SSN INTEGER UNIQUE,
    LastName VARCHAR(255),
    Position VARCHAR(5),
    LastServiceDate DATE DEFAULT CURRENT_DATE,
    StateCode CHAR(2) NOT NULL
);

-- Create a new INJURIES table
CREATE TABLE IF NOT EXISTS ENCOUNTERS (
    InjuryID INTEGER PRIMARY KEY AUTOINCREMENT,
    PatientSSN INTEGER NOT NULL,
    ICD10Code VARCHAR(7) NOT NULL,  -- Adjusted to accommodate typical ICD-10 codes (up to 7 characters)
    InjuryDate DATE NOT NULL,
    Description TEXT,
    FOREIGN KEY (PatientSSN) REFERENCES PATIENTS(SSN),
    FOREIGN KEY (ICD10Code) REFERENCES ICD10S(Code)
);
