DROP TABLE IF EXISTS [STATES];

-- schema.sql
CREATE TABLE IF NOT EXISTS STATES(
    CODE CHAR(2) PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PatientData (
    PatientID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    MiddleInitial CHAR(1),
    LastName TEXT NOT NULL,
    SSN CHAR(11) UNIQUE NOT NULL,
    Address TEXT NOT NULL,
    City TEXT NOT NULL,
    StateCode CHAR(2) NOT NULL,
    Zip CHAR(10) NOT NULL,
    FOREIGN KEY(StateCode) REFERENCES STATES(CODE)
);
