DROP TABLE IF EXISTS [STATES];
DROP TABLE IF EXISTS [ICD10S];
DROP TABLE IF EXISTS [PATIENTS];

-- schema.sql
CREATE TABLE IF NOT EXISTS STATES(
    CODE CHAR(2) PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL
);

-- Create ICD10S table
CREATE TABLE ICD10S (
    Code VARCHAR(3) PRIMARY KEY,
    Description VARCHAR(255)
);

-- Create PATIENTS table
CREATE TABLE PATIENTS (
    SSN INT UNIQUE,
    LastName VARCHAR(255),
    Position VARCHAR(5),
    LastServiceDate DATE
    Address TEXT NOT NULL,
    City TEXT NOT NULL,
    StateCode CHAR(2) NOT NULL,
    Zip CHAR(10) NOT NULL,
    FOREIGN KEY(StateCode) REFERENCES STATES(CODE)
);
